import React from "react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const links = [
    {
      name: "User",
      url: "signin",
    },
    {
      name: "Admin",
      url: "/admin/signin",
    },
    {
      name: "Librarian",
      url: "/librarian/signin",
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"flex justify-center items-center h-screen"}>
        {links.map((el) => (
          <Link href={el.url} key={el.url} passHref={true}>
            <button
              className={
                "px-4 text-center border-purple-500 border rounded mx-2 text-purple-500 hover:text-white hover:bg-purple-500 transition duration-300 py-2"
              }
            >
              {el.name}
            </button>
          </Link>
        ))}
      </div>
    </div>
  );
}
